appname: "JavaSparkDemo"
master_set: "local[*]"
loglevel: "Warn"
data_export_path: "/Users/songyunlong/Desktop/company/数据治理/数据质量管理/数据/附件8. 数据值缺失.xlsx"
data_save_path: "/Users/songyunlong/Desktop/spark_java/check_null"
data_save_style: "csv"
need_structType: true
need_check_col_name: "address_id"
data_source: "excel"
col_name:
  - "id"
  - "code"
  - "name"
  - "region_id"
  - "coordinate_x"
  - "coordinate_y"
  - "property_type_id"
  - "area_type_id"
  - "address_id"
  - "address_name"
  - "parent_id"
  - "spec_id"
  - "is_valid"